version: 2
project_name: danmaku-tool
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: main.go
    binary: danmaku
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
      - darwin_arm64
      - darwin_amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X danmu-tool/internal/config.Version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

dockers_v2:
  - id: danmaku-tool
    images:
      - "ghcr.io/lostars/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "latest"

    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.version": "{{.Version}}"

    dockerfile: Dockerfile

    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^feat:"
    - title: "Bug & Fixes"
      regexp: "^fix:"
    - title: "Changes"
      regexp: ".*"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^code:'