// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: danmaku.iqiyi.proto

package iqiyi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderAvatar   string                 `protobuf:"bytes,1,opt,name=senderAvatar,proto3" json:"senderAvatar,omitempty"`
	Uid            string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Udid           string                 `protobuf:"bytes,3,opt,name=udid,proto3" json:"udid,omitempty"`
	AvatarVipLevel string                 `protobuf:"bytes,4,opt,name=avatarVipLevel,proto3" json:"avatarVipLevel,omitempty"`
	AvatarId       string                 `protobuf:"bytes,5,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	PicL           string                 `protobuf:"bytes,7,opt,name=picL,proto3" json:"picL,omitempty"`
	Desc           string                 `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	NameColor      string                 `protobuf:"bytes,9,opt,name=nameColor,proto3" json:"nameColor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_danmaku_iqiyi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_iqiyi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_danmaku_iqiyi_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetSenderAvatar() string {
	if x != nil {
		return x.SenderAvatar
	}
	return ""
}

func (x *UserInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserInfo) GetUdid() string {
	if x != nil {
		return x.Udid
	}
	return ""
}

func (x *UserInfo) GetAvatarVipLevel() string {
	if x != nil {
		return x.AvatarVipLevel
	}
	return ""
}

func (x *UserInfo) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetPicL() string {
	if x != nil {
		return x.PicL
	}
	return ""
}

func (x *UserInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UserInfo) GetNameColor() string {
	if x != nil {
		return x.NameColor
	}
	return ""
}

type MinVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPhone        string                 `protobuf:"bytes,1,opt,name=iPhone,proto3" json:"iPhone,omitempty"`
	IPad          string                 `protobuf:"bytes,2,opt,name=iPad,proto3" json:"iPad,omitempty"`
	GPhone        string                 `protobuf:"bytes,3,opt,name=GPhone,proto3" json:"GPhone,omitempty"`
	GPad          string                 `protobuf:"bytes,4,opt,name=GPad,proto3" json:"GPad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinVersion) Reset() {
	*x = MinVersion{}
	mi := &file_danmaku_iqiyi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinVersion) ProtoMessage() {}

func (x *MinVersion) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_iqiyi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinVersion.ProtoReflect.Descriptor instead.
func (*MinVersion) Descriptor() ([]byte, []int) {
	return file_danmaku_iqiyi_proto_rawDescGZIP(), []int{1}
}

func (x *MinVersion) GetIPhone() string {
	if x != nil {
		return x.IPhone
	}
	return ""
}

func (x *MinVersion) GetIPad() string {
	if x != nil {
		return x.IPad
	}
	return ""
}

func (x *MinVersion) GetGPhone() string {
	if x != nil {
		return x.GPhone
	}
	return ""
}

func (x *MinVersion) GetGPad() string {
	if x != nil {
		return x.GPad
	}
	return ""
}

type BulletInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ContentId string                 `protobuf:"bytes,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	// 弹幕内容
	Content      string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParentId     string `protobuf:"bytes,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	GagEventId   string `protobuf:"bytes,4,opt,name=gagEventId,proto3" json:"gagEventId,omitempty"`
	GagResources string `protobuf:"bytes,5,opt,name=gagResources,proto3" json:"gagResources,omitempty"`
	// offset 秒
	ShowTime string `protobuf:"bytes,6,opt,name=showTime,proto3" json:"showTime,omitempty"`
	// 字体大小
	Font string `protobuf:"bytes,7,opt,name=font,proto3" json:"font,omitempty"`
	// FFFFFF 颜色
	Color string `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	// 透明度
	Opacity string `protobuf:"bytes,9,opt,name=opacity,proto3" json:"opacity,omitempty"`
	// 位置 0 是默认弹幕，顶部？
	Position    string `protobuf:"bytes,10,opt,name=position,proto3" json:"position,omitempty"`
	Background  string `protobuf:"bytes,11,opt,name=background,proto3" json:"background,omitempty"`
	ContentType string `protobuf:"bytes,12,opt,name=contentType,proto3" json:"contentType,omitempty"`
	IsReply     string `protobuf:"bytes,13,opt,name=isReply,proto3" json:"isReply,omitempty"`
	// 点赞数
	LikeCount        string      `protobuf:"bytes,14,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	PlusCount        string      `protobuf:"bytes,15,opt,name=plusCount,proto3" json:"plusCount,omitempty"`
	DissCount        string      `protobuf:"bytes,16,opt,name=dissCount,proto3" json:"dissCount,omitempty"`
	UserInfo         *UserInfo   `protobuf:"bytes,17,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	IsShowLike       string      `protobuf:"bytes,18,opt,name=isShowLike,proto3" json:"isShowLike,omitempty"`
	MinVersion       *MinVersion `protobuf:"bytes,20,opt,name=minVersion,proto3" json:"minVersion,omitempty"`
	MentionedTvid    string      `protobuf:"bytes,21,opt,name=mentionedTvid,proto3" json:"mentionedTvid,omitempty"`
	MentionedTitle   string      `protobuf:"bytes,22,opt,name=mentionedTitle,proto3" json:"mentionedTitle,omitempty"`
	SubType          string      `protobuf:"bytes,23,opt,name=subType,proto3" json:"subType,omitempty"`
	SnsTopicId       string      `protobuf:"bytes,24,opt,name=snsTopicId,proto3" json:"snsTopicId,omitempty"`
	SnsTopicTitle    string      `protobuf:"bytes,25,opt,name=snsTopicTitle,proto3" json:"snsTopicTitle,omitempty"`
	Src              string      `protobuf:"bytes,26,opt,name=src,proto3" json:"src,omitempty"`
	Spoiler          string      `protobuf:"bytes,27,opt,name=spoiler,proto3" json:"spoiler,omitempty"`
	HalfScreenShow   string      `protobuf:"bytes,28,opt,name=halfScreenShow,proto3" json:"halfScreenShow,omitempty"`
	ThemeId          string      `protobuf:"bytes,29,opt,name=themeId,proto3" json:"themeId,omitempty"`
	ThemeHead        string      `protobuf:"bytes,30,opt,name=themeHead,proto3" json:"themeHead,omitempty"`
	ThemeMiddle      string      `protobuf:"bytes,31,opt,name=themeMiddle,proto3" json:"themeMiddle,omitempty"`
	ThemeTail        string      `protobuf:"bytes,32,opt,name=themeTail,proto3" json:"themeTail,omitempty"`
	ScoreLevel       string      `protobuf:"bytes,33,opt,name=scoreLevel,proto3" json:"scoreLevel,omitempty"`
	SongId           string      `protobuf:"bytes,34,opt,name=songId,proto3" json:"songId,omitempty"`
	IsFirstWaterFall string      `protobuf:"bytes,35,opt,name=isFirstWaterFall,proto3" json:"isFirstWaterFall,omitempty"`
	VotePicture      string      `protobuf:"bytes,36,opt,name=votePicture,proto3" json:"votePicture,omitempty"`
	Score            string      `protobuf:"bytes,49,opt,name=score,proto3" json:"score,omitempty"`
	SpoilerGuess     string      `protobuf:"bytes,53,opt,name=spoilerGuess,proto3" json:"spoilerGuess,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BulletInfo) Reset() {
	*x = BulletInfo{}
	mi := &file_danmaku_iqiyi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletInfo) ProtoMessage() {}

func (x *BulletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_iqiyi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletInfo.ProtoReflect.Descriptor instead.
func (*BulletInfo) Descriptor() ([]byte, []int) {
	return file_danmaku_iqiyi_proto_rawDescGZIP(), []int{2}
}

func (x *BulletInfo) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *BulletInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BulletInfo) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *BulletInfo) GetGagEventId() string {
	if x != nil {
		return x.GagEventId
	}
	return ""
}

func (x *BulletInfo) GetGagResources() string {
	if x != nil {
		return x.GagResources
	}
	return ""
}

func (x *BulletInfo) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *BulletInfo) GetFont() string {
	if x != nil {
		return x.Font
	}
	return ""
}

func (x *BulletInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *BulletInfo) GetOpacity() string {
	if x != nil {
		return x.Opacity
	}
	return ""
}

func (x *BulletInfo) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *BulletInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *BulletInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BulletInfo) GetIsReply() string {
	if x != nil {
		return x.IsReply
	}
	return ""
}

func (x *BulletInfo) GetLikeCount() string {
	if x != nil {
		return x.LikeCount
	}
	return ""
}

func (x *BulletInfo) GetPlusCount() string {
	if x != nil {
		return x.PlusCount
	}
	return ""
}

func (x *BulletInfo) GetDissCount() string {
	if x != nil {
		return x.DissCount
	}
	return ""
}

func (x *BulletInfo) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *BulletInfo) GetIsShowLike() string {
	if x != nil {
		return x.IsShowLike
	}
	return ""
}

func (x *BulletInfo) GetMinVersion() *MinVersion {
	if x != nil {
		return x.MinVersion
	}
	return nil
}

func (x *BulletInfo) GetMentionedTvid() string {
	if x != nil {
		return x.MentionedTvid
	}
	return ""
}

func (x *BulletInfo) GetMentionedTitle() string {
	if x != nil {
		return x.MentionedTitle
	}
	return ""
}

func (x *BulletInfo) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *BulletInfo) GetSnsTopicId() string {
	if x != nil {
		return x.SnsTopicId
	}
	return ""
}

func (x *BulletInfo) GetSnsTopicTitle() string {
	if x != nil {
		return x.SnsTopicTitle
	}
	return ""
}

func (x *BulletInfo) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *BulletInfo) GetSpoiler() string {
	if x != nil {
		return x.Spoiler
	}
	return ""
}

func (x *BulletInfo) GetHalfScreenShow() string {
	if x != nil {
		return x.HalfScreenShow
	}
	return ""
}

func (x *BulletInfo) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *BulletInfo) GetThemeHead() string {
	if x != nil {
		return x.ThemeHead
	}
	return ""
}

func (x *BulletInfo) GetThemeMiddle() string {
	if x != nil {
		return x.ThemeMiddle
	}
	return ""
}

func (x *BulletInfo) GetThemeTail() string {
	if x != nil {
		return x.ThemeTail
	}
	return ""
}

func (x *BulletInfo) GetScoreLevel() string {
	if x != nil {
		return x.ScoreLevel
	}
	return ""
}

func (x *BulletInfo) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *BulletInfo) GetIsFirstWaterFall() string {
	if x != nil {
		return x.IsFirstWaterFall
	}
	return ""
}

func (x *BulletInfo) GetVotePicture() string {
	if x != nil {
		return x.VotePicture
	}
	return ""
}

func (x *BulletInfo) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *BulletInfo) GetSpoilerGuess() string {
	if x != nil {
		return x.SpoilerGuess
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int           string                 `protobuf:"bytes,1,opt,name=int,proto3" json:"int,omitempty"`
	BulletInfo    []*BulletInfo          `protobuf:"bytes,2,rep,name=bulletInfo,proto3" json:"bulletInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_danmaku_iqiyi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_iqiyi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_danmaku_iqiyi_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetInt() string {
	if x != nil {
		return x.Int
	}
	return ""
}

func (x *Entry) GetBulletInfo() []*BulletInfo {
	if x != nil {
		return x.BulletInfo
	}
	return nil
}

type Danmu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A00000 代表成功
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 弹幕总数
	Sum string `protobuf:"bytes,2,opt,name=sum,proto3" json:"sum,omitempty"`
	// 有效弹幕数量
	ValidSum string `protobuf:"bytes,3,opt,name=validSum,proto3" json:"validSum,omitempty"`
	// 视频时长 s
	Duration string `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	// 时间 2025-10-29 23:48:03
	Ts            string   `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	Entry         []*Entry `protobuf:"bytes,6,rep,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Danmu) Reset() {
	*x = Danmu{}
	mi := &file_danmaku_iqiyi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Danmu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Danmu) ProtoMessage() {}

func (x *Danmu) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_iqiyi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Danmu.ProtoReflect.Descriptor instead.
func (*Danmu) Descriptor() ([]byte, []int) {
	return file_danmaku_iqiyi_proto_rawDescGZIP(), []int{4}
}

func (x *Danmu) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Danmu) GetSum() string {
	if x != nil {
		return x.Sum
	}
	return ""
}

func (x *Danmu) GetValidSum() string {
	if x != nil {
		return x.ValidSum
	}
	return ""
}

func (x *Danmu) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Danmu) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *Danmu) GetEntry() []*Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_danmaku_iqiyi_proto protoreflect.FileDescriptor

const file_danmaku_iqiyi_proto_rawDesc = "" +
	"\n" +
	"\x13danmaku.iqiyi.proto\x12\x05danmu\"\xf2\x01\n" +
	"\bUserInfo\x12\"\n" +
	"\fsenderAvatar\x18\x01 \x01(\tR\fsenderAvatar\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04udid\x18\x03 \x01(\tR\x04udid\x12&\n" +
	"\x0eavatarVipLevel\x18\x04 \x01(\tR\x0eavatarVipLevel\x12\x1a\n" +
	"\bavatarId\x18\x05 \x01(\tR\bavatarId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04picL\x18\a \x01(\tR\x04picL\x12\x12\n" +
	"\x04desc\x18\b \x01(\tR\x04desc\x12\x1c\n" +
	"\tnameColor\x18\t \x01(\tR\tnameColor\"d\n" +
	"\n" +
	"MinVersion\x12\x16\n" +
	"\x06iPhone\x18\x01 \x01(\tR\x06iPhone\x12\x12\n" +
	"\x04iPad\x18\x02 \x01(\tR\x04iPad\x12\x16\n" +
	"\x06GPhone\x18\x03 \x01(\tR\x06GPhone\x12\x12\n" +
	"\x04GPad\x18\x04 \x01(\tR\x04GPad\"\x90\t\n" +
	"\n" +
	"BulletInfo\x12\x1c\n" +
	"\tcontentId\x18\x01 \x01(\tR\tcontentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bparentId\x18\x03 \x01(\tR\bparentId\x12\x1e\n" +
	"\n" +
	"gagEventId\x18\x04 \x01(\tR\n" +
	"gagEventId\x12\"\n" +
	"\fgagResources\x18\x05 \x01(\tR\fgagResources\x12\x1a\n" +
	"\bshowTime\x18\x06 \x01(\tR\bshowTime\x12\x12\n" +
	"\x04font\x18\a \x01(\tR\x04font\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x18\n" +
	"\aopacity\x18\t \x01(\tR\aopacity\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"background\x18\v \x01(\tR\n" +
	"background\x12 \n" +
	"\vcontentType\x18\f \x01(\tR\vcontentType\x12\x18\n" +
	"\aisReply\x18\r \x01(\tR\aisReply\x12\x1c\n" +
	"\tlikeCount\x18\x0e \x01(\tR\tlikeCount\x12\x1c\n" +
	"\tplusCount\x18\x0f \x01(\tR\tplusCount\x12\x1c\n" +
	"\tdissCount\x18\x10 \x01(\tR\tdissCount\x12+\n" +
	"\buserInfo\x18\x11 \x01(\v2\x0f.danmu.UserInfoR\buserInfo\x12\x1e\n" +
	"\n" +
	"isShowLike\x18\x12 \x01(\tR\n" +
	"isShowLike\x121\n" +
	"\n" +
	"minVersion\x18\x14 \x01(\v2\x11.danmu.MinVersionR\n" +
	"minVersion\x12$\n" +
	"\rmentionedTvid\x18\x15 \x01(\tR\rmentionedTvid\x12&\n" +
	"\x0ementionedTitle\x18\x16 \x01(\tR\x0ementionedTitle\x12\x18\n" +
	"\asubType\x18\x17 \x01(\tR\asubType\x12\x1e\n" +
	"\n" +
	"snsTopicId\x18\x18 \x01(\tR\n" +
	"snsTopicId\x12$\n" +
	"\rsnsTopicTitle\x18\x19 \x01(\tR\rsnsTopicTitle\x12\x10\n" +
	"\x03src\x18\x1a \x01(\tR\x03src\x12\x18\n" +
	"\aspoiler\x18\x1b \x01(\tR\aspoiler\x12&\n" +
	"\x0ehalfScreenShow\x18\x1c \x01(\tR\x0ehalfScreenShow\x12\x18\n" +
	"\athemeId\x18\x1d \x01(\tR\athemeId\x12\x1c\n" +
	"\tthemeHead\x18\x1e \x01(\tR\tthemeHead\x12 \n" +
	"\vthemeMiddle\x18\x1f \x01(\tR\vthemeMiddle\x12\x1c\n" +
	"\tthemeTail\x18  \x01(\tR\tthemeTail\x12\x1e\n" +
	"\n" +
	"scoreLevel\x18! \x01(\tR\n" +
	"scoreLevel\x12\x16\n" +
	"\x06songId\x18\" \x01(\tR\x06songId\x12*\n" +
	"\x10isFirstWaterFall\x18# \x01(\tR\x10isFirstWaterFall\x12 \n" +
	"\vvotePicture\x18$ \x01(\tR\vvotePicture\x12\x14\n" +
	"\x05score\x181 \x01(\tR\x05score\x12\"\n" +
	"\fspoilerGuess\x185 \x01(\tR\fspoilerGuess\"L\n" +
	"\x05Entry\x12\x10\n" +
	"\x03int\x18\x01 \x01(\tR\x03int\x121\n" +
	"\n" +
	"bulletInfo\x18\x02 \x03(\v2\x11.danmu.BulletInfoR\n" +
	"bulletInfo\"\x99\x01\n" +
	"\x05Danmu\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\tR\x03sum\x12\x1a\n" +
	"\bvalidSum\x18\x03 \x01(\tR\bvalidSum\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x0e\n" +
	"\x02ts\x18\x05 \x01(\tR\x02ts\x12\"\n" +
	"\x05entry\x18\x06 \x03(\v2\f.danmu.EntryR\x05entryB\bZ\x06/iqiyib\x06proto3"

var (
	file_danmaku_iqiyi_proto_rawDescOnce sync.Once
	file_danmaku_iqiyi_proto_rawDescData []byte
)

func file_danmaku_iqiyi_proto_rawDescGZIP() []byte {
	file_danmaku_iqiyi_proto_rawDescOnce.Do(func() {
		file_danmaku_iqiyi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_danmaku_iqiyi_proto_rawDesc), len(file_danmaku_iqiyi_proto_rawDesc)))
	})
	return file_danmaku_iqiyi_proto_rawDescData
}

var file_danmaku_iqiyi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_danmaku_iqiyi_proto_goTypes = []any{
	(*UserInfo)(nil),   // 0: danmu.UserInfo
	(*MinVersion)(nil), // 1: danmu.MinVersion
	(*BulletInfo)(nil), // 2: danmu.BulletInfo
	(*Entry)(nil),      // 3: danmu.Entry
	(*Danmu)(nil),      // 4: danmu.Danmu
}
var file_danmaku_iqiyi_proto_depIdxs = []int32{
	0, // 0: danmu.BulletInfo.userInfo:type_name -> danmu.UserInfo
	1, // 1: danmu.BulletInfo.minVersion:type_name -> danmu.MinVersion
	2, // 2: danmu.Entry.bulletInfo:type_name -> danmu.BulletInfo
	3, // 3: danmu.Danmu.entry:type_name -> danmu.Entry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_danmaku_iqiyi_proto_init() }
func file_danmaku_iqiyi_proto_init() {
	if File_danmaku_iqiyi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_iqiyi_proto_rawDesc), len(file_danmaku_iqiyi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_danmaku_iqiyi_proto_goTypes,
		DependencyIndexes: file_danmaku_iqiyi_proto_depIdxs,
		MessageInfos:      file_danmaku_iqiyi_proto_msgTypes,
	}.Build()
	File_danmaku_iqiyi_proto = out.File
	file_danmaku_iqiyi_proto_goTypes = nil
	file_danmaku_iqiyi_proto_depIdxs = nil
}
