// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: danmaku.bilibili.proto

package bilibili

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 弹幕颜色类型枚举 (DmColorfulType)
type DmColorfulType int32

const (
	DmColorfulType_NoneType        DmColorfulType = 0     // 无
	DmColorfulType_VipGradualColor DmColorfulType = 60001 // 渐变色
)

// Enum value maps for DmColorfulType.
var (
	DmColorfulType_name = map[int32]string{
		0:     "NoneType",
		60001: "VipGradualColor",
	}
	DmColorfulType_value = map[string]int32{
		"NoneType":        0,
		"VipGradualColor": 60001,
	}
)

func (x DmColorfulType) Enum() *DmColorfulType {
	p := new(DmColorfulType)
	*p = x
	return p
}

func (x DmColorfulType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DmColorfulType) Descriptor() protoreflect.EnumDescriptor {
	return file_danmaku_bilibili_proto_enumTypes[0].Descriptor()
}

func (DmColorfulType) Type() protoreflect.EnumType {
	return &file_danmaku_bilibili_proto_enumTypes[0]
}

func (x DmColorfulType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DmColorfulType.Descriptor instead.
func (DmColorfulType) EnumDescriptor() ([]byte, []int) {
	return file_danmaku_bilibili_proto_rawDescGZIP(), []int{0}
}

type DmSegMobileReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 弹幕列表
	Elems []*DanmakuElem `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	// 是否已关闭弹幕
	// 0:未关闭 1:已关闭
	State int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	// 弹幕云屏蔽ai评分值
	AiFlag        *DanmakuAIFlag `protobuf:"bytes,3,opt,name=ai_flag,json=aiFlag,proto3" json:"ai_flag,omitempty"`
	ColorfulSrc   []*DmColorful  `protobuf:"bytes,5,rep,name=colorfulSrc,proto3" json:"colorfulSrc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmSegMobileReply) Reset() {
	*x = DmSegMobileReply{}
	mi := &file_danmaku_bilibili_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmSegMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmSegMobileReply) ProtoMessage() {}

func (x *DmSegMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_bilibili_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmSegMobileReply.ProtoReflect.Descriptor instead.
func (*DmSegMobileReply) Descriptor() ([]byte, []int) {
	return file_danmaku_bilibili_proto_rawDescGZIP(), []int{0}
}

func (x *DmSegMobileReply) GetElems() []*DanmakuElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

func (x *DmSegMobileReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *DmSegMobileReply) GetAiFlag() *DanmakuAIFlag {
	if x != nil {
		return x.AiFlag
	}
	return nil
}

func (x *DmSegMobileReply) GetColorfulSrc() []*DmColorful {
	if x != nil {
		return x.ColorfulSrc
	}
	return nil
}

// 弹幕条目 (DanmakuElem)
type DanmakuElem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 弹幕dmid
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 弹幕出现位置(单位ms)
	Progress int32 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
	Mode int32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// 弹幕字号
	Fontsize int32 `protobuf:"varint,4,opt,name=fontsize,proto3" json:"fontsize,omitempty"`
	// 弹幕颜色
	Color uint32 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	// 发送者mid hash
	MidHash string `protobuf:"bytes,6,opt,name=midHash,proto3" json:"midHash,omitempty"`
	// 弹幕正文
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	// 发送时间
	Ctime int64 `protobuf:"varint,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 权重 用于屏蔽等级 区间:[1,10]
	Weight int32 `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	// 动作
	Action string `protobuf:"bytes,10,opt,name=action,proto3" json:"action,omitempty"`
	// 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
	Pool int32 `protobuf:"varint,11,opt,name=pool,proto3" json:"pool,omitempty"`
	// 弹幕dmid str
	IdStr string `protobuf:"bytes,12,opt,name=idStr,proto3" json:"idStr,omitempty"`
	// 弹幕属性位(bin求AND)
	// bit0:保护 bit1:直播 bit2:高赞
	Attr      int32  `protobuf:"varint,13,opt,name=attr,proto3" json:"attr,omitempty"`
	Animation string `protobuf:"bytes,22,opt,name=animation,proto3" json:"animation,omitempty"`
	// 大会员专属颜色
	Colorful      DmColorfulType `protobuf:"varint,24,opt,name=colorful,proto3,enum=bilibili.community.service.dm.v1.DmColorfulType" json:"colorful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuElem) Reset() {
	*x = DanmakuElem{}
	mi := &file_danmaku_bilibili_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuElem) ProtoMessage() {}

func (x *DanmakuElem) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_bilibili_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuElem.ProtoReflect.Descriptor instead.
func (*DanmakuElem) Descriptor() ([]byte, []int) {
	return file_danmaku_bilibili_proto_rawDescGZIP(), []int{1}
}

func (x *DanmakuElem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DanmakuElem) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DanmakuElem) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DanmakuElem) GetFontsize() int32 {
	if x != nil {
		return x.Fontsize
	}
	return 0
}

func (x *DanmakuElem) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *DanmakuElem) GetMidHash() string {
	if x != nil {
		return x.MidHash
	}
	return ""
}

func (x *DanmakuElem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DanmakuElem) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *DanmakuElem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DanmakuElem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DanmakuElem) GetPool() int32 {
	if x != nil {
		return x.Pool
	}
	return 0
}

func (x *DanmakuElem) GetIdStr() string {
	if x != nil {
		return x.IdStr
	}
	return ""
}

func (x *DanmakuElem) GetAttr() int32 {
	if x != nil {
		return x.Attr
	}
	return 0
}

func (x *DanmakuElem) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *DanmakuElem) GetColorful() DmColorfulType {
	if x != nil {
		return x.Colorful
	}
	return DmColorfulType_NoneType
}

// 弹幕ai云屏蔽列表 (DanmakuAIFlag)
type DanmakuAIFlag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 弹幕ai云屏蔽条目
	DmFlags       []*DanmakuFlag `protobuf:"bytes,1,rep,name=dm_flags,json=dmFlags,proto3" json:"dm_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuAIFlag) Reset() {
	*x = DanmakuAIFlag{}
	mi := &file_danmaku_bilibili_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuAIFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuAIFlag) ProtoMessage() {}

func (x *DanmakuAIFlag) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_bilibili_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuAIFlag.ProtoReflect.Descriptor instead.
func (*DanmakuAIFlag) Descriptor() ([]byte, []int) {
	return file_danmaku_bilibili_proto_rawDescGZIP(), []int{2}
}

func (x *DanmakuAIFlag) GetDmFlags() []*DanmakuFlag {
	if x != nil {
		return x.DmFlags
	}
	return nil
}

// 弹幕ai云屏蔽条目 (DanmakuFlag)
type DanmakuFlag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 弹幕dmid
	Dmid int64 `protobuf:"varint,1,opt,name=dmid,proto3" json:"dmid,omitempty"`
	// 评分
	Flag          uint32 `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuFlag) Reset() {
	*x = DanmakuFlag{}
	mi := &file_danmaku_bilibili_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuFlag) ProtoMessage() {}

func (x *DanmakuFlag) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_bilibili_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuFlag.ProtoReflect.Descriptor instead.
func (*DanmakuFlag) Descriptor() ([]byte, []int) {
	return file_danmaku_bilibili_proto_rawDescGZIP(), []int{3}
}

func (x *DanmakuFlag) GetDmid() int64 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *DanmakuFlag) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

// 弹幕颜色信息 (DmColorful)
type DmColorful struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DmColorfulType         `protobuf:"varint,1,opt,name=type,proto3,enum=bilibili.community.service.dm.v1.DmColorfulType" json:"type,omitempty"` // 颜色类型
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`                                                         //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DmColorful) Reset() {
	*x = DmColorful{}
	mi := &file_danmaku_bilibili_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmColorful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmColorful) ProtoMessage() {}

func (x *DmColorful) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_bilibili_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmColorful.ProtoReflect.Descriptor instead.
func (*DmColorful) Descriptor() ([]byte, []int) {
	return file_danmaku_bilibili_proto_rawDescGZIP(), []int{4}
}

func (x *DmColorful) GetType() DmColorfulType {
	if x != nil {
		return x.Type
	}
	return DmColorfulType_NoneType
}

func (x *DmColorful) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

var File_danmaku_bilibili_proto protoreflect.FileDescriptor

const file_danmaku_bilibili_proto_rawDesc = "" +
	"\n" +
	"\x16danmaku.bilibili.proto\x12 bilibili.community.service.dm.v1\"\x87\x02\n" +
	"\x10DmSegMobileReply\x12C\n" +
	"\x05elems\x18\x01 \x03(\v2-.bilibili.community.service.dm.v1.DanmakuElemR\x05elems\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12H\n" +
	"\aai_flag\x18\x03 \x01(\v2/.bilibili.community.service.dm.v1.DanmakuAIFlagR\x06aiFlag\x12N\n" +
	"\vcolorfulSrc\x18\x05 \x03(\v2,.bilibili.community.service.dm.v1.DmColorfulR\vcolorfulSrc\"\xa3\x03\n" +
	"\vDanmakuElem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\x12\x1a\n" +
	"\bfontsize\x18\x04 \x01(\x05R\bfontsize\x12\x14\n" +
	"\x05color\x18\x05 \x01(\rR\x05color\x12\x18\n" +
	"\amidHash\x18\x06 \x01(\tR\amidHash\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x14\n" +
	"\x05ctime\x18\b \x01(\x03R\x05ctime\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\tR\x06action\x12\x12\n" +
	"\x04pool\x18\v \x01(\x05R\x04pool\x12\x14\n" +
	"\x05idStr\x18\f \x01(\tR\x05idStr\x12\x12\n" +
	"\x04attr\x18\r \x01(\x05R\x04attr\x12\x1c\n" +
	"\tanimation\x18\x16 \x01(\tR\tanimation\x12L\n" +
	"\bcolorful\x18\x18 \x01(\x0e20.bilibili.community.service.dm.v1.DmColorfulTypeR\bcolorful\"Y\n" +
	"\rDanmakuAIFlag\x12H\n" +
	"\bdm_flags\x18\x01 \x03(\v2-.bilibili.community.service.dm.v1.DanmakuFlagR\admFlags\"5\n" +
	"\vDanmakuFlag\x12\x12\n" +
	"\x04dmid\x18\x01 \x01(\x03R\x04dmid\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\rR\x04flag\"d\n" +
	"\n" +
	"DmColorful\x12D\n" +
	"\x04type\x18\x01 \x01(\x0e20.bilibili.community.service.dm.v1.DmColorfulTypeR\x04type\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src*5\n" +
	"\x0eDmColorfulType\x12\f\n" +
	"\bNoneType\x10\x00\x12\x15\n" +
	"\x0fVipGradualColor\x10\xe1\xd4\x03B\vZ\t/bilibilib\x06proto3"

var (
	file_danmaku_bilibili_proto_rawDescOnce sync.Once
	file_danmaku_bilibili_proto_rawDescData []byte
)

func file_danmaku_bilibili_proto_rawDescGZIP() []byte {
	file_danmaku_bilibili_proto_rawDescOnce.Do(func() {
		file_danmaku_bilibili_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_danmaku_bilibili_proto_rawDesc), len(file_danmaku_bilibili_proto_rawDesc)))
	})
	return file_danmaku_bilibili_proto_rawDescData
}

var file_danmaku_bilibili_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_danmaku_bilibili_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_danmaku_bilibili_proto_goTypes = []any{
	(DmColorfulType)(0),      // 0: bilibili.community.service.dm.v1.DmColorfulType
	(*DmSegMobileReply)(nil), // 1: bilibili.community.service.dm.v1.DmSegMobileReply
	(*DanmakuElem)(nil),      // 2: bilibili.community.service.dm.v1.DanmakuElem
	(*DanmakuAIFlag)(nil),    // 3: bilibili.community.service.dm.v1.DanmakuAIFlag
	(*DanmakuFlag)(nil),      // 4: bilibili.community.service.dm.v1.DanmakuFlag
	(*DmColorful)(nil),       // 5: bilibili.community.service.dm.v1.DmColorful
}
var file_danmaku_bilibili_proto_depIdxs = []int32{
	2, // 0: bilibili.community.service.dm.v1.DmSegMobileReply.elems:type_name -> bilibili.community.service.dm.v1.DanmakuElem
	3, // 1: bilibili.community.service.dm.v1.DmSegMobileReply.ai_flag:type_name -> bilibili.community.service.dm.v1.DanmakuAIFlag
	5, // 2: bilibili.community.service.dm.v1.DmSegMobileReply.colorfulSrc:type_name -> bilibili.community.service.dm.v1.DmColorful
	0, // 3: bilibili.community.service.dm.v1.DanmakuElem.colorful:type_name -> bilibili.community.service.dm.v1.DmColorfulType
	4, // 4: bilibili.community.service.dm.v1.DanmakuAIFlag.dm_flags:type_name -> bilibili.community.service.dm.v1.DanmakuFlag
	0, // 5: bilibili.community.service.dm.v1.DmColorful.type:type_name -> bilibili.community.service.dm.v1.DmColorfulType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_danmaku_bilibili_proto_init() }
func file_danmaku_bilibili_proto_init() {
	if File_danmaku_bilibili_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_bilibili_proto_rawDesc), len(file_danmaku_bilibili_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_danmaku_bilibili_proto_goTypes,
		DependencyIndexes: file_danmaku_bilibili_proto_depIdxs,
		EnumInfos:         file_danmaku_bilibili_proto_enumTypes,
		MessageInfos:      file_danmaku_bilibili_proto_msgTypes,
	}.Build()
	File_danmaku_bilibili_proto = out.File
	file_danmaku_bilibili_proto_goTypes = nil
	file_danmaku_bilibili_proto_depIdxs = nil
}
