#  弹幕保存路径 只作用于CLI模式
save-path: ""
debug: true
# dandan api模式
# real_time 实时
# database sqlite数据库
dandan-mode: "real_time"
dandan-timeout: 60 # dandan api timeout in seconds
ua: "" # 请求ua 可不配置
# 分词器配置 用于提升识别准确率 关闭则直接注射掉即可
tokenizer:
  # 搜索结果标题黑名单 regex正则匹配搜索结果标题 replacement 则是需要替换为的词 提升匹配精准度
  # mode 后续标题匹配模式 默认不修改 后续匹配流程较长 该字段可影响最后一步匹配标题的模式 可选 equals ignore contains
  # 下面的示例规则可直接使用
  # 该黑名单配置只是影响某些平台黑名单词汇，保证其能继续匹配流程
  # 因为有年份、季和各自平台不同的过滤规则，不一定能保证搜索或者自动匹配出数据
  blacklist:
      # 该字段为正则表达式，特殊字符注意转义 用于匹配平台搜索结果的标题
    - regex: "(刺客)*伍六七.*记忆碎片"
      # 该字段用于替换的标题，直接修改为媒体库中的标题即可
      # 如果需要季信息 则添加 第x季
      replacement: "刺客伍六七第五季"
    - regex: "(刺客)*伍六七.*暗影宿命"
      replacement: "刺客伍六七第四季"
    - regex: "(刺客)*伍六七.*玄武国篇"
      replacement: "刺客伍六七第三季"
    - regex: "(刺客)*伍六七.*最强发型师"
      replacement: "刺客伍六七第二季"
    - regex: "(刺客)*伍六七"
      replacement: "刺客伍六七"
    - regex: "仙剑奇侠传\\s*第*\\s*(一|1)\\s*部*"
      # 生效平台 不配置则默认全平台生效
      platform: "youku"
      replacement: "仙剑奇侠传"
    - regex: "仙剑云之凡\\(仙剑奇侠传5\\)"
      platform: "youku"
      replacement: "仙剑奇侠传五"
  # 年份匹配规则 用于媒体年份匹配规则 主要用于媒体库年份信息和弹幕网站不一致
  # 配置后，对应的搜索标题则不会再从emby等元数据提供商获取年份信息
  # 相同 title-season/title 只会生效一次
  year-match-list:
      # 媒体标题 搜索的标题，即媒体库中的标题
    - title: "吞噬星空"
      # 不配置则生效于整个剧集
      season: 1
      # 如果year<=0或者不配置则表示不进行年份匹配
      year: 2020
  # 手动映射平台剧集信息 匹配到剧集信息后按照此处规则对剧集信息重新映射
  # 不影响搜索接口结果 作用于dandan /match 接口 提升自动匹配准确度
  rematch:
    - platform: "tencent"
      # 平台媒体id
      media-id: "xxq"
      # 匹配媒体库剧集id，按照顺序排列ep
      # 和 episodes 互斥 同时配置会使用 targets 配置
      # 用于处理平台一部剧对应多部媒体库中的剧集
      # 比如 火影忍者 在腾讯是 一部剧 但是在tmdb中是 2部剧
      targets:
          # 媒体库里对应剧集id
        - item: ""
          # 目前仅支持emby
          source: "emby"
          # 是否整个剧集统一编号 即 S01E01 S02E11
          union: true
      # 将平台剧集ep重新映射
      # 常见场景就是 某些S0剧集 平台是放在某一季的结尾 提升S0的匹配度
      # 该配置也可用于和媒体库中的剧集手动映射
      episodes:
          # 新的季id
        - season: 1
          # 对应ep列表 支持范围 1-100 用英文逗号隔开
          # 这里的id是指平台剧集列表里的id 如果列表内没有数字id，则使用在列表中的位置进行编号(数组下标+1)
          # 新的ep id 将会按照这里设置的顺序进行重新排序，从1开始
          episode: "1-100,200,201,202"
        - season: 2
          episode: "203-300,301"
server:
#  dandan api token 配置
  tokens:
    - "xxx"
    - "aaa"
  timeout: 10
  port: 8089
#  emby 配置，用于更加精准的搜索。注意token权限，系统使用用户API进行搜索，不要给管理员TOKEN
emby:
  url: ""
  user: ""
  token: ""
#  目前可选 bilibili tencent youku iqiyi 配置均通用
platforms:
  - name: "bilibili"
  #  优先级 用于控制剧集搜索结果 越小则排的更靠前(int) <0 则禁用该平台
    priority: 10
  #  完整cookie 否则部分接口不出数据
    cookie: ""
  #  单个视频弹幕下载的并发数 调高了注意账号风险 用的b站6min一段的弹幕接口，调高了意义也不大
    max-worker: 4 # 默认4
  #  请求超时时间 单位：秒
    timeout: 10
    # 合并毫秒内重复弹幕 单位 ms <=0则不启用 同时作用于弹幕抓取和dandan api
    merge-danmaku-in-mills: 1000
    # 弹幕保存文件类型 xml 或者 ass
    persists: ["xml", "ass"]
  - name: "tencent"
    priority: 100
    cookie: "xxx" # 最好提供，否则可能会导致搜不到数据
    max-worker: 4
    timeout: 10
    merge-danmaku-in-mills: 1000
    persists: ["xml", "ass"]